apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmChart
metadata:
  name: helmchart-sample
spec:
  chart: podinfo
  version: '^2.0.0'
  sourceRef:
    kind: HelmRepository
    name: helmrepository-sample
  interval: 1m
