apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmChart
metadata:
  name: helmchart-sample
spec:
  name: podinfo
  version: '>=2.0.0 <3.0.0'
  helmRepositoryRef:
    name: helmrepository-sample
  interval: 1m
